###
POST http://127.0.0.1:8081/api/v3/AI_recommendations
Content-Type: application/json

[
  49026,
  155,
  312113
]
###
POST http://127.0.0.1:8090/api/v3/add/1234/blep
###
GET http://127.0.0.1:8090/api/v3/get/blep
###
POST http://127.0.0.1:8090/api/v3/add/6666/blop
###
POST http://127.0.0.1:8090/api/v3/rate_movie/1234/155/4
###
POST http://127.0.0.1:8090/api/v3/rate_movie/6666/155/5
###
POST http://127.0.0.1:8090/api/v3/rate_movie/1234/19995/5
###
GET http://localhost:8082/api/get_movie_ratings/155
###
GET http://localhost:8082/api/get_number_of_ratings
###
GET http://localhost:8082/api/get_users_number
###
GET http://localhost:8082/api/get_movie_rating_avg/155
###
